### ISSUE TITLE
Google Pixel 6 Pro unable to pair to Helium Miners

### ISSUE THREAD

**Issue by BigPimpin1369** [helium/hotspot-app#1172]
**Describe the bug**
When trying to pair to a Helium Miner via Bluetooth, the Helium app states "error, disconnected" 

**To Reproduce**

1. Go to 'Helium app
2. Click on miner name, then click on gear icon (settings), then click on Update Wi-Fi or Run Diagnostics, then the blue Pair button
3. Select miner to pair too
4. See error "error, disconected"

**Expected behavior**
The ability to pair to miners via Bluetooth on Google Pixel Pro 6 phones 

**Screenshots**
Helium app does not allow for screen shots anymore

**Smartphone (please complete the following information):**

- Device: Google Pixel Pro 6
- Bluetooth Protocol v5.2
- OS: Android 12
- App Version v3.8.5

**Additional context**
Please get this resolved, as newer phones come out every year, it would be of importance to the helium team to have updated Bluetooth protocol updated in the Helium app.  The last phone I had that I was able to use and pair with was a Pixel 3 XL. I do not have access to that phone anymore.  I have several miners and more coming in soon and need the ability to pair to them!

**Comment by cokes518** [comment]
Hi @BigPimpin1369 I'm trying to reproduce this - can you let me know what brand Hotspot you're trying to connect to?

**Comment by BigPimpin1369** [comment]
Coca,

sensecap m1.

Thank you

**Comment by cokes518** [comment]
The issue seems to be with SenseCaps. There is a known issue where Samsung devices cannot pair with SenseCap M1 miners (it looks like it's more Android devices now, including Pixel 6), but other devices can. 

I just tested this:
Pixel 6 -> SenseCap: fail
Pixel 6 -> Helium Hotspot: connects
Pixel 6 -> MNTD Hotspot: connects
iOS -> SenseCap: connects
Samsung -> SenseCap: fail
Samsung -> MNTD Hotspot: connects

The incapability is not with the app, but with how android phones connects to SenseCaps and there's no code in the app that can be changed to fix this.

**Comment by BigPimpin1369** [comment]
Interesting, so on my old Pixel 3xl I was able to connect just fine.  So
you think it is the Bluetooth protocol that the Pixel 6 has? Nothing that
Sensecap or Helium can do and it is on Google and Samsung to fix?

**Comment by cokes518** [comment]
I don't think it's the protocol on the pixel 6 (since it does pair with other hotspot types), but rather the compatibility between sensecaps and some androids, specifically.

**Comment by cokes518** [comment]
All of that is to say, the new bluetooth version 5.2 is not the culprit.

**Comment by BigPimpin1369** [comment]
So it is on sensecap to fix this? I reached out to them and they are
blaming it on Helium. Thus why I put in the bug ticket.

I see a tennis match of accountability about to happen here.

**Comment by cokes518** [comment]
I'll have our engineers double check the logs just in case there is something we can do, for completeness.

**Comment by BigPimpin1369** [comment]
Ah, I forgotten about sensecap having an app. I will have to check that
out.  I hope I can onboard my two miners getting here today.

**Comment by tyler-whitman** [comment]
@BigPimpin1369 can you please let us know the exact error message you see in the dialog. You mentioned "error, disconected", is it a longer message or thats it?

**Comment by BigPimpin1369** [comment]
Sure. I will get the exact wording for you in a bit.  Currently at work so
no access to the miner.  Pretty sure that is what the error was and what
looked like a Mac address after the error message.

**Comment by cokes518** [comment]
no need @BigPimpin1369 I have a sensecap and reproduced for our engineer.

to triple confirm that it's not the app, I downloaded LightBlue https://play.google.com/store/apps/details?id=com.punchthrough.lightblueexplorer&hl=en_US&gl=US and was also unable to pair with the sensecap. I recommend you try the same so you can see for yourself.

**Comment by BigPimpin1369** [comment]
Thank you. I will be able try later on today after work. I will update you
all once I am able to get to the miner.

**Comment by StephenDillon** [comment]
Also ran into this using a pixel 6 pro, 6 and my older oneplus phones with both the sensecap and helium app for Android. (M1 as well)

**Comment by StephenDillon** [comment]
![Screenshot_20220111-163908~2](https://user-images.githubusercontent.com/1057182/149025853-9871ee28-2511-4d85-b61a-0938ad42713f.png)

**Comment by KillingJacky** [comment]
SenseCAP dev here. 
This issue has more to do with protocol incompatibility. It could be at least one party not following the protocol standard tightly, it could be those Android devices which adopt newer BLE protocol, it could be Balena OS which is used by SenseCAP. Since it's protocol layer I don't think there's much the App could do, it's more OS related. We'll work with the Balena OS team to seek a solution. Before that, please find another phone to finish the hotspot assertion. Very sorry for this inconvenience.

**Comment by BigPimpin1369** [comment]
Jack,

Thank you for the follow up.  I tried to pair to a new sensecap m1 miner
last night, and no joy.  I wish I had my old phone still.  Maybe I can use
the wife's pixel 4 till this is resolved.

If I do use my wife's phone, I would have to put in the 12 words.  What
happens to the wallet on my current phone?  Will I still be able to access
it?

Thank you .

**Comment by KillingJacky** [comment]
I think you can still open and operate the Helium App on your current phone. The wallet can be accessed from multiple phones if you input the correct 12 words.

**Comment by cokes518** [comment]
closing this as it's not an app issue. Please check with sensecap on when pixel/samsung support is available for your devices.

**Comment by BigPimpin1369** [comment]
Ok, thanks.

**Comment by Myke500** [comment]
> SenseCAP dev here. This issue has more to do with protocol incompatibility. 

I can confirm that this is still an issue as of today **(2022/07/30).** 
Helium app is not the issue, but from the Sensecap M1 to the Pixel6. 
It is not Bluetooth discoverable on **Pixel6 pro**, the app does discover the Sensecap M1, then disconnects in an error state.  The Pixel6 BLE menu never shows the Sensecap as an option.

Likewise a **Pixel4 XL** running Android 12 is able to discover and connect to the Sensecap M1. (Similar to the recommendation of using an older Samsung device to connect)

BLE Info **Pixel4 XL**:
AVRCP ver. 1.5
MAP ver. 1.2

BLE Info Pixel6 pro:
AVRCP ver. 1.5
MAP ver. 1.4

By downdating the MAP version to the older 1.2 format, the Pixel6 pro did appear to connect with the Sensecap M1 via the Helium app.  But it still does not show in the BLE list on the device.  (This should be tested as a possible solution.

**Comment by garrettpatterson** [comment]
Same issue today with Helium and SyncroB.it hotspot.  New Pixel 6a, Android 12

![image](https://user-images.githubusercontent.com/759479/186793833-0455f0eb-3d3e-4c9c-94db-b587b784d993.png)
